CREATE TYPE CDMOTIVOCANCTO_TYPE AS ENUM (
  'PACIENTE_DESISTIU',
  'MEDICO_CANCELOU',
  'OUTROS'
);

CREATE TYPE ESPECIALIDADE_TYPE AS ENUM (
  'ORTOPEDIA',
  'CARDIOLOGIA',
  'GINECOLOGIA',
  'DERMATOLOGIA'
);

CREATE TABLE MEDICO
(
  ID SERIAL PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  TELEFONE VARCHAR(30) NOT NULL,
  CRM VARCHAR(30) NOT NULL,
  ESPEC ESPECIALIDADE_TYPE,
  LOGRADOURO VARCHAR(100),
  NUMERO VARCHAR(30),
  COMPLEMENTO VARCHAR(100),
  BAIRRO VARCHAR(100),
  CIDADE VARCHAR(100),
  UF VARCHAR(2),
  CEP VARCHAR(20),
  ATIVO BOOLEAN DEFAULT TRUE
);

CREATE TABLE PACIENTE
(
  ID SERIAL PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  TELEFONE VARCHAR(30) NOT NULL,
  CPF VARCHAR(11) NOT NULL,
  LOGRADOURO VARCHAR(100),
  NUMERO VARCHAR(30),
  COMPLEMENTO VARCHAR(100),
  BAIRRO VARCHAR(100),
  CIDADE VARCHAR(100),
  UF VARCHAR(2),
  CEP VARCHAR(20),
  ATIVO BOOLEAN DEFAULT TRUE
);

CREATE TABLE CONSULTA
(
  ID SERIAL PRIMARY KEY,
  ID_PACIENTE INTEGER NOT NULL REFERENCES PACIENTE(ID),
  ID_MEDICO INTEGER NOT NULL REFERENCES MEDICO(ID),
  DATAHORA TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  CD_MOTIVOCANCTO CDMOTIVOCANCTO_TYPE,
  DS_MOTIVOCANCTO VARCHAR(500)
);
